### PR TITLE
ANA support

### PR DESCRIPTION
**Pull request by hreinecke**
Hi all,

here's a patchset to implement and test ANA support for NVMe.
Nothing special, really, but nice to have as this functionality is use quite heavily in storage arrays and hence should be tested, too.

### CODE REVIEW

**Comment by kawasaki** [comment]
@hreinecke I'm trying to run this test case on my system and observe failure. nvme connect fails and kernel reports an error:
```
[ 3441.943356][ T2668] nvmet: connect request for invalid subsystem blktests-subsystem-1!
[ 3441.948225][ T2732] nvme nvme7: Connect Invalid Data Parameter, subsysnqn "blktests-subsystem-1"
```
I will look in further. If you have any advice to make the test case pass, please let me know.

**Comment by hreinecke** [comment]
> @hreinecke I'm trying to run this test case on my system and observe failure. nvme connect fails and kernel reports an error:
> 
> ```
> [ 3441.943356][ T2668] nvmet: connect request for invalid subsystem blktests-subsystem-1!
> [ 3441.948225][ T2732] nvme nvme7: Connect Invalid Data Parameter, subsysnqn "blktests-subsystem-1"
> ```
> 
> I will look in further. If you have any advice to make the test case pass, please let me know.

This might be due to an old/outdated nvme-cli. There was a version which had problem connecting to nvme-loop devices.
Please see if an update (ideally to nvme-cli v2.0) is required.

**Comment by kawasaki** [comment]
> > @hreinecke I'm trying to run this test case on my system and observe failure. nvme connect fails and kernel reports an error:
> > ```
> > [ 3441.943356][ T2668] nvmet: connect request for invalid subsystem blktests-subsystem-1!
> > [ 3441.948225][ T2732] nvme nvme7: Connect Invalid Data Parameter, subsysnqn "blktests-subsystem-1"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will look in further. If you have any advice to make the test case pass, please let me know.
> 
> This might be due to an old/outdated nvme-cli. There was a version which had problem connecting to nvme-loop devices. Please see if an update (ideally to nvme-cli v2.0) is required.

Thanks for the advice, but nvme-cli version may not be the cause. I'm using Fedora 36, and it has nvme-cli package v2.0. To ensure, I have built latest nvme-cli from source code an installed on the test system, but still I observe the failure. FYI, nvme --version says "nvme version 2.0 (git 2.0)" and "libnvme version 1.0 (git 1.0-40-g5ba1e59)". Hmm.

**Comment by hreinecke** [comment]
Superseded by PR#113

**Pull request closed without merging**
