### PR TITLE
block/031: remove the fio verify.state file

### PR DESCRIPTION
**Pull request by yizhanglinux**
Remove the fio verify.state file local-block-031-0-verify.state after fio finished

### CODE REVIEW

**Comment by kawasaki** [comment]
@yizhanglinux Thank you for catching this! The file should not be left.

As for the solution, how about to add "--verify_state_save=0" option to the fio command? This approach does not create the file, then a bit cleaner than "create the file and remove it".

```
diff --git a/tests/block/031 b/tests/block/031
index 5ad6d88..99615ec 100755
--- a/tests/block/031
+++ b/tests/block/031
@@ -45,7 +45,7 @@ test() {
                --ioengine=libaio --runtime="${TIMEOUT}" --thread \
                --name=block-031 --filename=/dev/nullb1 \
                --output="${RESULTS_DIR}/block/fio-output-031.txt" \
-               >>"$FULL"
+               --verify_state_save=0 >>"$FULL"
        fio_status=$?
        rmdir /sys/kernel/config/nullb/nullb1
        _exit_null_blk
```

**Comment by yizhanglinux** [comment]
> @yizhanglinux Thank you for catching this! The file should not be left.
> 
> As for the solution, how about to add "--verify_state_save=0" option to the fio command? This approach does not create the file, then a bit cleaner than "create the file and remove it".
> 
> ```
> diff --git a/tests/block/031 b/tests/block/031
> index 5ad6d88..99615ec 100755
> --- a/tests/block/031
> +++ b/tests/block/031
> @@ -45,7 +45,7 @@ test() {
>                 --ioengine=libaio --runtime="${TIMEOUT}" --thread \
>                 --name=block-031 --filename=/dev/nullb1 \
>                 --output="${RESULTS_DIR}/block/fio-output-031.txt" \
> -               >>"$FULL"
> +               --verify_state_save=0 >>"$FULL"
>         fio_status=$?
>         rmdir /sys/kernel/config/nullb/nullb1
>         _exit_null_blk
> ```

Yeah, that's a better way, just pushed another two commit for the verify.state file cleanup.

**Comment by yizhanglinux** [comment]
++ @bvanassche

**Comment by kawasaki** [comment]
@yizhanglinux thanks, all three changes look good to me. I ran whole blktests, and did not see regression. One small nit change is the commit message of the 3rd commit. To fix it, I applied the three commits manually. Now they are in the master branch. Thank you!

**Pull request closed without merging**
